version: '1'

services:
  emersondb:
      image: 'emersonschulze/emersondb:latest'
    ports:
      - '3306:3306'
    volumes:
      - 'emersondb_data:/emersonschulze/emersondb'

volumes:
  emersondb_data:
    driver: local

    