version: '2'

services:
  emersondb-master:
    image: 'emersonschulze/emersondb:latest'
    ports:
      - '3306'
    volumes:
      - 'emersondb_master_data:/emersonschulze/emersondb'
    environment:
      - EMERSONDB_REPLICATION_MODE=master
      - EMERSONDB_REPLICATION_USER=repl_user
      - EMERSONDB_REPLICATION_PASSWORD=repl_password
      - EMERSONDB_USER=my_user
      - EMERSONDB_PASSWORD=my_password
      - EMERSONDB_DATABASE=my_database
  emersondb-slave:
    image: 'emersonschulze/emersondb:latest'
    ports:
      - '3306'
    depends_on:
      - emersondb-master
    environment:
      - EMERSONDB_REPLICATION_MODE=slave
      - EMERSONDB_REPLICATION_USER=repl_user
      - EMERSONDB_REPLICATION_PASSWORD=repl_password
      - EMERSONDB_MASTER_HOST=emersondb-master
      - EMERSONDB_MASTER_PORT=3306
      - EMERSONDB_USER=my_user
      - EMERSONDB_PASSWORD=my_password
      - EMERSONDB_DATABASE=my_database

volumes:
  emersondb_master_data:
    driver: local
